services:
  traefik:
    container_name: traefik
    image: traefik:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: 
      - --certificatesresolvers.myresolver.acme.email=${EMAIL_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=traefik@docker
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - traefik_letsencrypt:/etc/letsencrypt
    networks:
      - traefik
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: -H unix:///var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.tls.certresolver=myresolver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  portainer_data:
  traefik_letsencrypt:
