api:
  dashboard: true
  insecure: true # Desabilita o dashboard inseguro

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https # Redireciona HTTP para HTTPS

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    exposedByDefault: false # Impede a exposição automática de containers

certificatesResolvers:
  myresolver:
    acme:
      storage: /etc/letsencrypt/acme.json
      # Uncomment this line to enable the TLS challenge just if your domain supports CAA records and you have configured them correctly.
      # tlsChallenge: {} 
