api:
  dashboard: true
  insecure: true # Desabilita o dashboard inseguro

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https # Redireciona HTTP para HTTPS

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  swarm:
    endpoint: "tcp://127.0.0.1:2377"

certificatesResolvers:
  myresolver:
    acme:
      storage: /etc/letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      # Uncomment this line to enable the TLS challenge just if your domain supports CAA records and you have configured them correctly.
      # tlsChallenge: {} 
